# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 14:28
from __future__ import unicode_literals

import common.fields
import common.utils.generate
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TachyPosition',
            fields=[
                ('position_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensors.Position')),
            ],
            bases=('sensors.position',),
        ),
        migrations.CreateModel(
            name='TachySensor',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensors.Sensor')),
                ('sensor_model', models.PositiveSmallIntegerField(choices=[(101, b'Leica 1100-Series'), (102, b'Leica 1200-Series'), (103, b'Leica TS15'), (104, b'Leica TM30'), (105, b'Leica TM50'), (901, b'Simulated Tachymeter')], default=11)),
            ],
            bases=('sensors.sensor',),
        ),
        migrations.CreateModel(
            name='TachyStation',
            fields=[
                ('id', common.fields.IdField(db_index=True, default=common.utils.generate.generate_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('easting', models.FloatField()),
                ('northing', models.FloatField()),
                ('height', models.FloatField()),
                ('von', models.DateTimeField(default=datetime.datetime.now)),
                ('bis', models.DateTimeField(default=datetime.datetime.now)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tachy.TachyPosition')),
            ],
            options={
                'ordering': ['position', 'von'],
            },
        ),
        migrations.CreateModel(
            name='TachyTarget',
            fields=[
                ('target_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensors.Target')),
                ('target_type', models.CharField(choices=[(b'd', b'Deformationspunkt'), (b'f', b'Festpunkt')], default='d', max_length=1)),
                ('prism_type', models.PositiveSmallIntegerField(choices=[(0, b'Leica Rundprisma'), (1, b'Leica Miniprisma'), (2, b'Leica Reflektorfolie'), (3, b'Leica 360'), (7, b'Leica Miniprisma 360'), (11, b'kein Prisma')], default=1)),
            ],
            options={
                'ordering': ['target_type', 'name'],
            },
            bases=('sensors.target',),
        ),
        migrations.CreateModel(
            name='TachyTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.Task')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tachy.TachyPosition')),
                ('targets', models.ManyToManyField(to='tachy.TachyTarget')),
            ],
            bases=('tasks.task',),
        ),
    ]
