# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 00:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tachy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tachysensor',
            name='model_type',
            field=models.PositiveSmallIntegerField(choices=[(11, b'Leica 1100-Series'), (12, b'Leica 1200-Series'), (13, b'Leica TS15'), (14, b'Leica TM30'), (15, b'Leica TM50')], default=11),
        ),
        migrations.AlterField(
            model_name='tachystation',
            name='bis',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 21, 1, 2, 12, 80291)),
        ),
        migrations.AlterField(
            model_name='tachystation',
            name='von',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 21, 1, 2, 12, 80246)),
        ),
    ]
