# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 00:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tachy', '0003_auto_20160121_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tachysensor',
            old_name='model_type',
            new_name='sensor_model',
        ),
        migrations.AlterField(
            model_name='tachystation',
            name='bis',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 21, 1, 24, 46, 481917)),
        ),
        migrations.AlterField(
            model_name='tachystation',
            name='von',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 21, 1, 24, 46, 481871)),
        ),
    ]
