# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 00:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tachy', '0005_auto_20160121_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tachystation',
            name='bis',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 21, 1, 29, 29, 926070)),
        ),
        migrations.AlterField(
            model_name='tachystation',
            name='von',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 21, 1, 29, 29, 926023)),
        ),
    ]
