# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 00:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tachy', '0008_auto_20160121_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tachysensor',
            name='sensor_model',
            field=models.PositiveSmallIntegerField(choices=[(101, b'Leica 1100-Series'), (102, b'Leica 1200-Series'), (103, b'Leica TS15'), (104, b'Leica TM30'), (105, b'Leica TM50')], default=11),
        ),
        migrations.AlterField(
            model_name='tachystation',
            name='bis',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 21, 1, 31, 40, 3582)),
        ),
        migrations.AlterField(
            model_name='tachystation',
            name='von',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 21, 1, 31, 40, 3536)),
        ),
    ]
