# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 15:58
from __future__ import unicode_literals

import bitfield.models
import common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicTask',
            fields=[
                ('id', common.fields.UIDField(serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('frequency', models.DecimalField(decimal_places=1, default=10.0, max_digits=4)),
                ('day_of_week', bitfield.models.BitField((('0', 'monday'), ('1', 'tuesday'), ('2', 'wednesday'), ('3', 'thursday'), ('4', 'friday'), ('5', 'saturday'), ('6', 'sunday')), default=None)),
                ('object_id', models.CharField(db_index=True, max_length=10)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='active',
        ),
        migrations.RemoveField(
            model_name='task',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='task',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='task',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_time',
        ),
    ]
