# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 06:51
from __future__ import unicode_literals

import common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationType',
            fields=[
                ('id', common.fields.UIDField(serialize=False)),
                ('name', models.CharField(choices=[(b'dH', 'H\xf6hen\xe4nderung'), (b'dE', '\xc4nderung Rechtswert'), (b'dN', '\xc4nderung Hochwert'), (b'dl', 'L\xe4ngsverschiebung'), (b'dq', 'Querverschiebung'), (b'dS', 'Strecken\xe4nderung'), (b'dHz', '\xc4nderung Horizontalwinkel'), (b'dV', '\xc4nderung Vertikalwinkel')], max_length=20, unique=True)),
                ('unit', models.CharField(choices=[(b'm', b'Meter'), (b'dm', b'Dezimeter'), (b'cm', b'Zentimeter'), (b'mm', b'Millimeter'), (b'gon', b'Gon'), (b'mgon', b'Milligon')], max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('scale', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', common.fields.UIDField(serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.PositiveSmallIntegerField(choices=[(16, 'active'), (0, 'inactive')], db_index=True, default=16)),
                ('sensor_type', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='metering.Position')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', common.fields.UIDField(serialize=False)),
                ('sensor_name', models.CharField(max_length=100)),
                ('sensor_serial', models.CharField(max_length=20, unique=True)),
                ('sensor_model', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', common.fields.UIDField(serialize=False)),
                ('easting', models.FloatField(blank=True, db_index=True, null=True)),
                ('northing', models.FloatField(blank=True, db_index=True, null=True)),
                ('height', models.FloatField(blank=True, db_index=True, null=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='metering.Position')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='metering.Sensor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', common.fields.UIDField(serialize=False)),
                ('easting', models.FloatField(blank=True, db_index=True, null=True)),
                ('northing', models.FloatField(blank=True, db_index=True, null=True)),
                ('height', models.FloatField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=20)),
                ('status', models.PositiveSmallIntegerField(choices=[(16, 'active'), (0, 'inactive')], db_index=True, default=16)),
                ('positions', models.ManyToManyField(through='metering.Reference', to='metering.Position')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='reference',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='metering.Target'),
        ),
        migrations.AddField(
            model_name='position',
            name='sensors',
            field=models.ManyToManyField(through='metering.Station', to='metering.Sensor'),
        ),
    ]
