# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0002_auto_20160417_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='port',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
