# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0005_auto_20160419_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_model',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
