# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 00:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_name',
            field=models.CharField(default=datetime.datetime(2016, 1, 21, 0, 25, 16, 254007, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_serial',
            field=models.CharField(default=datetime.datetime(2016, 1, 21, 0, 25, 25, 468551, tzinfo=utc), max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
