# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 05:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_mail', models.BooleanField(default=True)),
                ('by_text', models.BooleanField(default=True)),
                ('by_light', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlarmPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(choices=[(-2, b'-ROT-'), (-1, b'-ORANGE-'), (0, b'+GRUEN+'), (1, b'+ORANGE+'), (2, b'+ROT+')], default=0)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AlarmPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[(b'u', b'User'), (b'm', b'Manager'), (b'a', b'Admin')], default=b'u', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ObservationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('scale', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(default=b'', max_length=255)),
                ('token', models.CharField(default=b'', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('members', models.ManyToManyField(through='setup.Membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easting', models.FloatField()),
                ('northing', models.FloatField()),
                ('height', models.FloatField()),
                ('name', models.CharField(max_length=30)),
                ('von', models.DateTimeField(default=datetime.datetime(2015, 12, 15, 6, 35, 47, 483190))),
                ('bis', models.DateTimeField(default=datetime.datetime(2015, 12, 15, 6, 35, 47, 483228))),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Position')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.Sensor')),
            ],
            options={
                'ordering': ['position', 'von'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easting', models.FloatField()),
                ('northing', models.FloatField()),
                ('height', models.FloatField()),
                ('name', models.CharField(max_length=20)),
                ('target_type', models.CharField(choices=[(b'd', b'Deformationspunkt'), (b'f', b'Festpunkt')], default=b'd', max_length=1)),
                ('prism_type', models.PositiveSmallIntegerField(choices=[(1, b'Miniprisma'), (7, b'Miniprisma 360')], default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Project')),
            ],
            options={
                'ordering': ['target_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Position')),
                ('targets', models.ManyToManyField(to='setup.Target')),
            ],
            options={
                'ordering': ['position', 'time_window'],
            },
        ),
        migrations.CreateModel(
            name='TimeWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('von', models.TimeField()),
                ('bis', models.TimeField()),
                ('frequency', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('day_of_week', models.CharField(default=b'1234567', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='time_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.TimeWindow'),
        ),
        migrations.AddField(
            model_name='position',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Project'),
        ),
        migrations.AddField(
            model_name='position',
            name='recent_sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.Sensor'),
        ),
        migrations.AddField(
            model_name='membership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Project'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='box',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.Project'),
        ),
        migrations.AddField(
            model_name='alarmplan',
            name='observation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.ObservationType'),
        ),
        migrations.AddField(
            model_name='alarmplan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Project'),
        ),
        migrations.AddField(
            model_name='alarmphase',
            name='alarm_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.AlarmPlan'),
        ),
        migrations.AddField(
            model_name='alarmnotification',
            name='alarm_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.AlarmPhase'),
        ),
        migrations.AddField(
            model_name='alarmnotification',
            name='boxes',
            field=models.ManyToManyField(to='setup.Box'),
        ),
        migrations.AddField(
            model_name='alarmnotification',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
