# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 21:09
from __future__ import unicode_literals

import bitfield.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', bitfield.models.BitField((b'Blinklicht',), default=None)),
                ('alarm_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.AlarmPhase')),
                ('boxes', models.ManyToManyField(to='setup.Box')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', bitfield.models.BitField((b'SMS', b'EMail'), default=None)),
                ('alarm_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.AlarmPhase')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='station',
            name='bis',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 16, 22, 9, 3, 221604)),
        ),
        migrations.AlterField(
            model_name='station',
            name='von',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 16, 22, 9, 3, 221560)),
        ),
        migrations.AlterField(
            model_name='timewindow',
            name='day_of_week',
            field=bitfield.models.BitField((b'Montag', b'Dienstag', b'Mittwoch', b'Donnerstag', b'Freitag', b'Samstag', b'Sonntag'), default=None),
        ),
    ]
