# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 21:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_auto_20151216_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarmphase',
            options={'ordering': ['alarm_plan', 'state']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='time_window',
        ),
        migrations.AddField(
            model_name='task',
            name='time_windows',
            field=models.ManyToManyField(to='setup.TimeWindow'),
        ),
        migrations.AlterField(
            model_name='station',
            name='bis',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 16, 22, 35, 26, 224798)),
        ),
        migrations.AlterField(
            model_name='station',
            name='von',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 16, 22, 35, 26, 224757)),
        ),
    ]
