# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 00:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_auto_20151215_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easting', models.FloatField()),
                ('northing', models.FloatField()),
                ('height', models.FloatField()),
                ('name', models.CharField(max_length=20)),
                ('target_type', models.CharField(choices=[(b'd', b'Deformationspunkt'), (b'f', b'Festpunkt')], default=b'd', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Position')),
                ('target', models.ManyToManyField(to='setup.Target')),
            ],
        ),
        migrations.CreateModel(
            name='TimeWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('von', models.DateTimeField(default=datetime.datetime(2015, 12, 15, 1, 29, 31, 431276))),
                ('bis', models.DateTimeField(default=datetime.datetime(2015, 12, 15, 1, 29, 31, 431321))),
                ('day_of_week', models.CharField(default=b'1234567', max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='station',
            name='bis',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 15, 1, 29, 31, 433520)),
        ),
        migrations.AlterField(
            model_name='station',
            name='von',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 15, 1, 29, 31, 433490)),
        ),
        migrations.AddField(
            model_name='task',
            name='time_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.TimeWindow'),
        ),
    ]
