# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 21:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_auto_20151216_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='bis',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 16, 22, 35, 51, 171334)),
        ),
        migrations.AlterField(
            model_name='station',
            name='von',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 16, 22, 35, 51, 171291)),
        ),
    ]
