# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 00:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_auto_20151215_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='bis',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 15, 1, 37, 52, 72926)),
        ),
        migrations.AlterField(
            model_name='station',
            name='von',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 15, 1, 37, 52, 72883)),
        ),
        migrations.AlterField(
            model_name='timewindow',
            name='bis',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timewindow',
            name='von',
            field=models.TimeField(),
        ),
    ]
