# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 00:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_auto_20151215_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='prism_type',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Miniprisma'), (7, b'Miniprisma 360')], default=1),
        ),
        migrations.AlterField(
            model_name='station',
            name='bis',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 15, 1, 46, 23, 461742)),
        ),
        migrations.AlterField(
            model_name='station',
            name='von',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 15, 1, 46, 23, 461701)),
        ),
    ]
