# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 00:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_auto_20151215_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setup.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='bis',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 15, 1, 48, 32, 301496)),
        ),
        migrations.AlterField(
            model_name='station',
            name='von',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 15, 1, 48, 32, 301456)),
        ),
    ]
