# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 01:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_auto_20151215_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='target',
            new_name='targets',
        ),
        migrations.AlterField(
            model_name='station',
            name='bis',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 15, 2, 12, 19, 242164)),
        ),
        migrations.AlterField(
            model_name='station',
            name='von',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 15, 2, 12, 19, 242125)),
        ),
    ]
