# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 01:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_auto_20151215_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='project',
            field=models.ForeignKey(blank=True, default=1, on_delete=models.SET(b''), to='setup.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='bis',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 15, 2, 18, 17, 113896)),
        ),
        migrations.AlterField(
            model_name='station',
            name='von',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 15, 2, 18, 17, 113856)),
        ),
    ]
