# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160121_0102'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([('user', 'project')]),
        ),
    ]
