# Return-Code names and return-code values
    # TPS
k = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
v = ['GRC_OK', 'GRC_UNDEFINED', 'GRC_IVPARAM', 'GRC_IVRESULT', 'GRC_FATAL',
     'GRC_NOT_IMPL', 'GRC_TIME_OUT', 'GRC_SET_INCOMPL', 'GRC_ABORT',
     'GRC_NOMEMORY', 'GRC_NOTINIT', 'GRC_SHUT_DOWN', 'GRC_SYSBUSY',
     'GRC_HWFAILURE', 'GRC_ABORT_APPL', 'GRC_LOW_POWER', 'GRC_IVVERSION',
     'GRC_BATT_EMPTY', 'GRC_NO_EVENT', 'GRC_OUT_OF_TEMP',
     'GRC_INSTRUMENT_TILT', 'GRC_COM_SETTING', 'GRC_NO_ACTION',
     'GRC_SLEEP_MODE', 'GRC_NOTOK', 'GRC_NA', 'GRC_OVERFLOW', 'GRC_STOPPED']
ReturnCodeDict = dict(zip(k, v))
    # ANG
k = [257, 258, 259, 260, 261, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275]
v = ['GRC_ANG_ERROR', 'GRC_ANG_INCL_ERROR', 'GRC_ANG_BAD_ACC',
     'GRC_ANG_BAD_ANGLE_ACC', 'GRC_ANG_BAD_INCLIN_ACC',
     'GRC_ANG_WRITE_PROTECTED', 'GRC_ANG_OUT_OF_RANGE', 'GRC_ANG_IR_OCCURED',
     'GRC_ANG_HZ_MOVED', 'GRC_ANG_OS_ERROR', 'GRC_ANG_DATA_ERROR',
     'GRC_ANG_PEAK_CNT_UFL', 'GRC_ANG_TIME_OUT', 'GRC_ANG_TOO_MANY_EXPOS',
     'GRC_ANG_PIX_CTRL_ERR']
ReturnCodeDict.update(dict(zip(k, v)))
k = [276, 277, 278, 279, 280, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 316, 317,
         326, 327, 328, 329, 330, 331]
v = ['GRC_ANG_MAX_POS_SKIP', 'GRC_ANG_MAX_NEG_SKIP', 'GRC_ANG_EXP_LIMIT',
     'GRC_ANG_UNDER_EXPOSURE', 'GRC_ANG_OVER_EXPOSURE', 'GRC_ANG_TMANY_PEAKS',
     'GRC_ANG_TLESS_PEAKS', 'GRC_ANG_PEAK_TOO_SLIM', 'GRC_ANG_PEAK_TOO_WIDE',
     'GRC_ANG_BAD_PEAKDIFF', 'GRC_ANG_UNDER_EXP_PICT',
     'GRC_ANG_PEAKS_INHOMOGEN', 'GRC_ANG_NO_DECOD_POSS',
     'GRC_ANG_UNSTABLE_DECOD', 'GRC_ANG_TLESS_FPEAKS',
     'GRC_ANG_INCL_OLD_PLANE', 'GRC_ANG_INCL_NO_PLANE',
     'GRC_ANG_FAST_ANG_ERR', 'GRC_ANG_FAST_ANG_ERR_5',
     'GRC_ANG_FAST_ANG_ERR_25', 'GRC_ANG_TRANS_ERR',
     'GRC_ANG_TRANS_ERR_5', 'GRC_ANG_TRANS_ERR_25']
ReturnCodeDict.update(dict(zip(k, v)))
    # ATA
    # k = [...]
    # v = [...]
    # ReturnCodeDict.update(dict(zip(k,v)))
    # EDM
    # k = [...]
    # v = [...]
    # ReturnCodeDict.update(dict(zip(k,v)))
    # TMC
k = [1283, 1284, 1285, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1380, 1381, 1392, 1383, 3081]
v = ['GRC_TMC_NO_FULL_CORRECTION', 'GRC_TMC_ACCURACY_GUARANTEE',
         'GRC_TMC_ANGLE_OK', 'GRC_TMC_ANGLE_NOT_FULL_CORR',
         'GRC_TMC_ANGLE_NO_ACC_GUARANTY', 'GRC_TMC_ANGLE_ERROR',
         'GRC_TMC_DIST_PPM', 'GRC_TMC_DIST_ERROR', 'GRC_TMC_BUSY',
         'GRC_TMC_SIGNAL_ERROR', 'GRC_OLD_PLANE', 'GRC_NO_PLANE',
         'GRC_INC_ERROR', 'GRC_INCLINE_ACC', 'GRC_COM_PROC_UNAVAIL']
ReturnCodeDict.update(dict(zip(k, v)))
    # MOT
k = [1792, 1793, 1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803]
v = ['GRC_MOT_UNREADY', 'GRC_MOT_BUSY', 'GRC_MOT_NOT_OCONST',
         'GRC_MOT_NOT_CONFIG', 'GRC_MOT_NOT_POSIT', 'GRC_MOT_NOT_SERVICE',
         'GRC_MOT_NOT_BUSY', 'GRC_MOT_NOT_LOCK', 'GRC_MOT_NOT_SPIRAL',
         'GRC_MOT_V_ENCODER', 'GRC_MOT_HZ_ENCODER', 'GRC_MOT_HZ_V_ENCODER']
ReturnCodeDict.update(dict(zip(k, v)))
    # COM
    # k = [...]
    # v = [...]
    # ReturnCodeDict.update(dict(zip(k,v)))
    # AUT
k = [8704, 8705, 8706, 8707, 8708, 8709, 8710, 8711, 8712, 8713, 8714, 8715, 8716, 8717,
         8718, 8719, 8720, 8721, 8722, 8723, 8724, 8725]
v = ['GRC_AUT_TIMEOUT', 'GRC_AUT_DETENT_ERROR', 'GRC_AUT_ANGLE_ERROR',
         'GRC_AUT_MOTOR_ERROR', 'GRC_AUT_INCACC', 'GRC_AUT_DEV_ERROR',
         'GRC_AUT_NO_TARGET', 'GRC_AUT_MULTIPLE_TARGETS',
         'GRC_AUT_BAD_ENVIRONMENT', 'GRC_AUT_DETECTOR_ERROR',
         'GRC_AUT_NOT_ENABLED', 'GRC_AUT_CALACC', 'GRC_AUT_ACCURACY',
         'GRC_AUT_DIST_STARTED', 'GRC_AUT_SUPPLY_TOO_HIGH',
         'GRC_AUT_SUPPLY_TOO_LOW', 'GRC_AUT_NO_WORKING_AREA',
         'GRC_AUT_ARRAY_FULL', 'GRC_AUT_NO_DATA', 'GRC_AUT_SIDECOVER_ERR',
         'GRC_AUT_OUT_OF_SYNC', 'GRC_AUT_NO_LOCK']
ReturnCodeDict.update(dict(zip(k, v)))
    # KDM
k = [12544]
v = ['GRC_KDM_NOT_AVAILABLE']
ReturnCodeDict.update(dict(zip(k, v)))
    # FTR
k = [13056, 13057, 13058, 13059, 13060]
v = ['GRC_FTR_FILEACCESS', 'GRC_FTR_WRONGFILEBLOCKNUMBE',
    'GRC_FTR_NOTENOUGHSPACE', 'GRC_FTR_INVALIDINPUT', 'GRC_FTR_MISSINGSETUP']
ReturnCodeDict.update(dict(zip(k, v)))
    # CAM
    # k = [...]
    # v = [...]
    # ReturnCodeDict.update(dict(zip(k,v)))
    
k = [-999]
v = ['NO_TPS_CONNECTION']
ReturnCodeDict.update(dict(zip(k, v)))
