# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tasks', '0002_auto_20160404_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default="1", on_delete=django.db.models.deletion.CASCADE, to='accounts.Project'),
            preserve_default=False,
        ),
    ]
