# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20160417_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodictask',
            name='last_started',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
