# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelSensor',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensors.Sensor')),
                ('sensor_model', models.PositiveSmallIntegerField(choices=[(201, b'Leica Nivel'), (202, b'Seika N10')], default=11)),
            ],
            bases=('sensors.sensor',),
        ),
    ]
