# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0002_auto_20160121_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelSensor',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensors.Sensor')),
                ('sensor_model', models.PositiveSmallIntegerField(choices=[(11, b'Leica 1100-Series'), (12, b'Leica 1200-Series'), (13, b'Leica TS15'), (14, b'Leica TM30'), (15, b'Leica TM50')], default=11)),
            ],
            bases=('sensors.sensor',),
        ),
    ]
