# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivelsensor',
            name='sensor_model',
            field=models.PositiveSmallIntegerField(choices=[(101, b'Leica 1100-Series'), (102, b'Leica 1200-Series'), (103, b'Leica TS15'), (104, b'Leica TM30'), (105, b'Leica TM50')], default=11),
        ),
    ]
