# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivel', '0002_auto_20160121_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivelsensor',
            name='sensor_model',
            field=models.PositiveSmallIntegerField(choices=[(201, b'Leica Nivel'), (202, b'Seika N10')], default=11),
        ),
    ]
